### ISSUE TITLE
Unable to get shell on existing running GPU containers

### ISSUE THREAD

**Issue by kumareshr** [NVIDIA/enroot#26]
I was trying to get a shell on running container but encountered this issue. not sure how gpu handled on pyxis & enroot. Below are the test cases 

something similar to : docker exec 

Case 1:[GPU job]
```
srun --pty -p debug  --gpus=1 --container-image=pytorch:19.10-py3  sleep 1000
slurmstepd: pyxis: running "enroot import" ...
slurmstepd: pyxis: running "enroot create" ...
slurmstepd: pyxis: running "enroot start" ...
slurmstepd: task_p_pre_launch: Using sched_affinity for tasks
```

```
srun --pty  --container-name=188639.0 --jobid=188639 bash
srun: Job 188639 step creation temporarily disabled, retrying
```

**If I use non-gpu container it works but if I use GPU container am not able get shell** 

Case 2: [Non -GPU continer] 

```
srun  --pty --container-image=ubuntu  sleep 1000
slurmstepd: pyxis: running "enroot import" ...
slurmstepd: pyxis: running "enroot create" ...
slurmstepd: pyxis: running "enroot start" ...
slurmstepd: task_p_pre_launch: Using sched_affinity for tasks
```

```
srun  --pty --container-name=1142.0 --jobid=1142 bash
slurmstepd: pyxis: reusing existing container
slurmstepd: pyxis: running "enroot start" ...
slurmstepd: task_p_pre_launch: Using sched_affinity for tasks
root@compute3:#
```

Case 3:[GPU Job]
```
 srun --pty  --gpus=1 --container-image=pytorch:19.10-py3  sleep 1000
slurmstepd: pyxis: running "enroot import" ...
slurmstepd: pyxis: running "enroot create" ...
slurmstepd: pyxis: running "enroot start" ...
slurmstepd: task_p_pre_launch: Using sched_affinity for tasks
```

with second srun slurm created a step with existing container but with --gups=0 below error occurred:

slurmstepd: error: pyxis:     [ERROR] /etc/enroot/hooks.d/98-nvidia.sh exited with return code 1

 ```
srun  --pty  --gpus=0 --container-name=1144.0 --jobid=1144 bash
slurmstepd: pyxis: reusing existing container
slurmstepd: pyxis: running "enroot start" ...
slurmstepd: error: pyxis: container start failed with error code: 1
slurmstepd: pyxis: printing contents of log file ...
slurmstepd: error: pyxis:     nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected
slurmstepd: error: pyxis:     [ERROR] /etc/enroot/hooks.d/98-nvidia.sh exited with return code 1
slurmstepd: error: spank: required plugin spank_pyxis.so: task_init_privileged() failed with rc=-1
slurmstepd: error: spank_task_init_privileged failed
slurmstepd: error: write to unblock task 0 failed: Broken pipe
srun: error: compute-dgx-03: task 0: Exited with exit code 1
srun: Terminating job step 1144.1
```

**Comment by 3XX0** [comment]
Can you try case 1 with `nvidia/cuda` as the image instead of Pytorch?

Case 3 won't work because you're not joining the first container, you're actually creating a separate container with the same root filesystem and starting it without GPUs.
Two solutions:
- Export `NVIDIA_VISIBLE_DEVICES=void` before the second srun to tell enroot not to use GPU support for this container
- Actually join the first container with `srun --pty --jobid=1144 enroot exec <pid> bash` where `<pid>` can be obtain through `scontrol listpids`

**Comment by kumareshr** [comment]
Solution 1: 
Thanks, this worked as expected but Hence we use gpu=none &  export NVIDIA_VISIBLE_DEVICES=void
can't access the GPU inside containers with the bash.

```
$ srun --pty  --gpus=1 --container-image=nvidia/cuda bash
slurmstepd: pyxis: running "enroot import" ...
slurmstepd: pyxis: running "enroot create" ...
slurmstepd: pyxis: running "enroot start" ...
slurmstepd: task_p_pre_launch: Using sched_affinity for tasks
root@compute-dgx-03:
```

```
cluster-login-01:~$ export NVIDIA_VISIBLE_DEVICES=void
cluster-login-01:~$ srun --pty  --gres=none --container-name=1150.0 --jobid=1150 bash
slurmstepd: pyxis: reusing existing container
slurmstepd: pyxis: running "enroot start" ...
slurmstepd: task_p_pre_launch: Using sched_affinity for tasks
root@compute-dgx-03:/# nvidia-smi
```
 Just wondering is anyway can we tell to enroot/pyxis don't check for GPU but just load drivers when try to get shell by using any env variables ?
for example: 
NVIDIA_VISIBLE_DEVICES=none
>  none: no GPU will be accessible, but driver capabilities will be enabled.
but 
```
cluster-login-01:~$ export NVIDIA_VISIBLE_DEVICES=none
cluster-login-01:~$ srun --pty  --gres=none --container-name=1150.0 --jobid=1150 bash
slurmstepd: pyxis: reusing existing container
slurmstepd: pyxis: running "enroot start" ...
slurmstepd: error: pyxis: container start failed with error code: 1
slurmstepd: pyxis: printing contents of log file ...
slurmstepd: error: pyxis:     nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected
slurmstepd: error: pyxis:     [ERROR] /etc/enroot/hooks.d/98-nvidia.sh exited with return code 1
slurmstepd: error: spank: required plugin spank_pyxis.so: task_init_privileged() failed with rc=-1
slurmstepd: error: spank_task_init_privileged failed
slurmstepd: error: write to unblock task 0 failed: Broken pipe
srun: error: compute-dgx-03: task 0: Exited with exit code 1
srun: Terminating job step 1150.13
```

Solution 2: 

```
compute-dgx-03:~$ scontrol listpid 1150
PID      JOBID    STEPID LOCALID GLOBALID
32959    1150     0      0       0       
-1       1150     4294967295 0       0       
32388    1150     4294967295 -       -       
```

Do we have enroot exec or is recently added other version ? encountered error, is something I missed ?!
```
cluster-login-01:~$ srun --pty --gpus=0 --jobid=1150 enroot exec 32959 bash
slurmstepd: task_p_pre_launch: Using sched_affinity for tasks
Usage: enroot COMMAND [ARG...]

Command line utility for manipulating container sandboxes.

 Commands:
   batch  [options] [--] CONFIG [COMMAND] [ARG...]
   bundle [options] [--] IMAGE
   create [options] [--] IMAGE
   export [options] [--] NAME
   import [options] [--] URI
   list   [options]
   remove [options] [--] NAME...
   start  [options] [--] NAME|IMAGE [COMMAND] [ARG...]
   version
```

**Comment by 3XX0** [comment]
1) You can't because at this point SLURM has isolated the GPUs even if we allowed passing the drivers it wouldn't work. I don't think you can share your GPU allocation between job steps with SLURM. Maybe `--oversubscribe` works with TRES but I'm not 100% sure. There is a similar issue [here](https://stackoverflow.com/questions/55186407/slurm-oversubscribe-gpus).

2) Unfortunately it requires enroot 3.0. Make sure to purge the enroot cache (`ENROOT_CACHE_PATH`) before you upgrade.

**Comment by kumareshr** [comment]
Thanks @3XX0 , I tried  `--oversubscribe`  affinity but no luck.

 ```
 srun --pty --oversubscribe --container-name=1159.0 --jobid=1159 bash
srun: Job 1159 step creation temporarily disabled, retrying
```
For now i will dig more available ways to share GPU b/w steps.

Future we will use the method 2 with enroot 3.0 upgrade.

**Comment by 3XX0** [comment]
Let me know how it goes.
You can also try configuring GPUs as Gres instead of using `--gpus`, although not ideal they might not get the same treatment when it comes to accounting.

**Comment by kumareshr** [comment]
I don't see easy way for this issue and looks slurm assigns the GPU for the step with "TRES_per_step" 
so when it creates second step there is no option to tell slurm use the old ters which assinged to the previous step. Getting more 

```
slurmctld: debug2: Processing RPC: REQUEST_JOB_PACK_ALLOC_INFO from uid=1000
slurmctld: debug:  _slurm_rpc_job_pack_alloc_info: JobId=1167 NodeList=compute-node-03 usec=28
slurmctld: debug3: StepDesc: user_id=1000 JobId=1167 StepId=4294967294 node_count=1-1 cpu_count=1 num_tasks=1
slurmctld: debug3:    cpu_freq_gov=4294967294 cpu_freq_max=4294967294 cpu_freq_min=4294967294 relative=65534 task_dist=0x1 plane=65534
slurmctld: debug3:    node_list=(null)  constraints=(null)
slurmctld: debug3:    host=cluster-login-01 port=33307 srun_pid=6165 name=bash network=(null) exclusive=0
slurmctld: debug3:    checkpoint-dir=(null) checkpoint_int=0
slurmctld: debug3:    mem_per_node=0 resv_port_cnt=65534 immediate=0 no_kill=0
slurmctld: debug3:    overcommit=0 time_limit=0
```
`slurmctld: debug3:    TRES_per_step=gpu:1`

`slurmctld: debug3: step_layout cpus = 10 pos = 0`

Since Enroot have feature to do enroot exec. I think we can close this bug

**Comment by kumareshr** [comment]
enroot exec shows below error.

`srun --pty --jobid=246 enroot exec 9546 bash                  `   

                                                                                                                  
slurmstepd: task_p_pre_launch: Using sched_affinity for tasks
**enroot-nsenter: failed to join cgroup namespace: Operation not permitted**
srun: error: compute-01: task 0: Exited with exit code 1
srun: Terminating job step 246.3

**Comment by kumareshr** [comment]
More strace info  : 

```
access("/usr/bin/enroot-nsenter", R_OK) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=12839, si_uid=13029, si_status=0, si_utime=0, si_stime=0} ---
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], WNOHANG, NULL) = 12839
wait4(-1, 0x7ffea923a6d0, WNOHANG, NULL) = -1 ECHILD (No child processes)
rt_sigreturn({mask=[]})                 = 0
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f14ca4eaf20}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f14ca4eaf20}, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f14ca4eaf20}, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f14ca4eaf20}, 8) = 0
rt_sigaction(SIGCHLD, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f14ca4eaf20}, {sa_handler=0x55bae3e07790, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f14ca4eaf20}, 8) = 0
execve("/usr/bin/enroot-nsenter", ["enroot-nsenter", "--target", "12142", "--user", "--mount", "--envfile", "/proc/self/fd/10", "--workdir", "/proc/12142/cwd", "bash"], 0x55bae5c9a8d0 /* 46 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x7f0a0104add8) = 0
set_tid_address(0x7f0a0104aff0)         = 12812
open("/proc/12142/ns/user", O_RDONLY)   = 3
setns(3, CLONE_NEWUSER)                 = 0
close(3)                                = 0
open("/proc/12142/ns/mnt", O_RDONLY)    = 3
setns(3, CLONE_NEWNS)                   = 0
close(3)                                = 0
open("/proc/12142/ns/cgroup", O_RDONLY) = 3
setns(3, CLONE_NEWCGROUP)               = -1 EPERM (Operation not permitted)
close(3)                                = 0
writev(2, [{iov_base="enroot-nsenter: ", iov_len=16}, {iov_base=NULL, iov_len=0}], 2enroot-nsenter: ) = 16
writev(2, [{iov_base="failed to join cgroup namespace", iov_len=31}, {iov_base=NULL, iov_len=0}], 2failed to join cgroup namespace) = 31
writev(2, [{iov_base="", iov_len=0}, {iov_base=": ", iov_len=2}], 2: ) = 2
writev(2, [{iov_base="", iov_len=0}, {iov_base="Operation not permitted", iov_len=23}], 2Operation not permitted) = 23
writev(2, [{iov_base="", iov_len=0}, {iov_base="\n", iov_len=1}], 2
) = 1
exit_group(1)                           = ?
+++ exited with 1 +++

```

**Comment by 3XX0** [comment]
What OS are you using?

It might be an issue in pyxis itself, does it work if you use `enroot start` and `enroot exec` manually?

**Comment by 3XX0** [comment]
So it looks like this is indeed an issue in pyxis, we'll need to fix it there.
I'll keep this issue open until the fix is ready.

**Comment by flx42** [comment]
Should be fixed with this pyxis commit: https://github.com/NVIDIA/pyxis/commit/f5bb79c1aa6bdb51896ad96cf5bcc6bd9e541c84

**Comment by commonism** [comment]
Can you please document how to get a shell in an existing/running enroot GPU container?
